// Vendor the same-origin runtime assets (PRD AC-P1: no CDN, all assets same-origin).
// Copies the Pyodide runtime out of node_modules into public/pyodide/, and zips the
// pure-Python engine package into public/pinewood_derby.zip so the bridge can load it
// into Pyodide's FS at boot. Both outputs are gitignored and regenerated by this script
// (run automatically before dev / build / test).
import { mkdirSync, copyFileSync, existsSync, rmSync } from "node:fs";
import { execSync } from "node:child_process";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(here, "..");
const appRoot = resolve(webRoot, "..");
const pyodideSrc = join(webRoot, "node_modules", "pyodide");
const pubPyodide = join(webRoot, "public", "pyodide");
const engineSrcDir = join(appRoot, "src");
const engineZip = join(webRoot, "public", "pinewood_derby.zip");

// The minimal set loadPyodide() needs to boot from a same-origin indexURL.
const RUNTIME = [
  "pyodide.mjs",
  "pyodide.asm.js",
  "pyodide.asm.wasm",
  "python_stdlib.zip",
  "pyodide-lock.json",
];

mkdirSync(pubPyodide, { recursive: true });
for (const f of RUNTIME) copyFileSync(join(pyodideSrc, f), join(pubPyodide, f));
console.log(`[vendor] ${RUNTIME.length} Pyodide runtime files -> public/pyodide/`);

if (existsSync(engineZip)) rmSync(engineZip);
execSync(`zip -r -q "${engineZip}" pinewood_derby -x "*__pycache__*" "*.pyc"`, {
  cwd: engineSrcDir,
  stdio: "inherit",
});
console.log("[vendor] engine -> public/pinewood_derby.zip");
